# Generated by Django 3.2.18 on 2023-03-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='newrecipe',
            name='creator',
        ),
    ]
